hw4-0001: home work 4
matkovskiy/golang_course pull request #2
Opened 2023-09-20 16:25 UTC by matkovskiy

2023-09-20 19:00 UTC, fotonmoton requested changes

2023-09-20 19:00 UTC, fotonmoton commented on HW4/pkg/sys_lib/sys_lib.go
> +func Read_file(file string) (lines []string) {
If you want simply read entire file you can use `os.ReadFile()` https://pkg.go.dev/os#ReadFile and then split string by `\n`

2023-09-20 19:00 UTC, fotonmoton commented on HW4/sys_lib/sys_lib.go
> +package sys_lib
Don't get it why you have multiple "sys_lib" packages. Seems like you copied it from previous homework. Also, try to avoid packages such as "sys_lib" which doesn't have exact responsibility, it's hard to understand from first sight what this package should do.

2023-09-21 11:01 UTC, matkovskiy commented on HW4/pkg/sys_lib/sys_lib.go
> +func Read_file(file string) (lines []string) {
Yes, but bufio does it instead of me. 
`	fileScanner.Split(bufio.ScanLines)
	for fileScanner.Scan() {
		lines = append(lines, fileScanner.Text())`

2023-09-21 13:30 UTC, matkovskiy commented on HW4/sys_lib/sys_lib.go
> +package sys_lib
Yes, you are right - fixed - https://github.com/matkovskiy/golang_course/pull/2/commits/56ee719b5e47fca203e5b9c32692e000c824a33c

2023-09-25 16:16 UTC, merged